branches:
  only:
    - master

os: osx
osx_image: xcode10.2
language: swift

env:
  global:
    - XCODE_WORKSPACE="FFUIKit/FFUIKit.xcworkspace"
    - XCODE_SCHEME=FFUIKit
    - XCODE_DESTINATION="platform=iOS Simulator,OS=12.2,name=iPad Pro (10.5-inch)"
script: ./scripts/build_xcode.sh
