branches:
  only:
    - master
    - develop

os: osx
osx_image: xcode10
language: swift

env:
  global:
    - XCODE_WORKSPACE="FFUIKit/FFUIKit.xcworkspace"
    - XCODE_SCHEME=FFUIKit
    - XCODE_DESTINATION="platform=iOS Simulator,OS=12.0,name=iPad Pro (9.7-inch)"
script: ./scripts/build_xcode.sh
